sudo: required
dist: xenial

language: go
go:
  - "1.11.x"
env:
  global:
    - GO111MODULE=on
    - LDFLAG="-X main.version=${TRAVIS_TAG} -X main.commit=${TRAVIS_COMMIT::6}"
  matrix:
    - TRUFFLE_VERSION=truffle  # latest truffle with solidity v0.5.x
    - TRUFFLE_VERSION=truffle@4.1.14  # truffle@4.1.14 with solidity v0.4.x

cache:
  directories:
    - $GOPATH/pkg/mod
    - test/solidity/node_modules
  
install:
  # install protobuf
  - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o protoc.zip
  - unzip protoc.zip -d protoc
  - sudo mv protoc/bin/* /usr/local/bin/
  - sudo mv protoc/include/* /usr/local/include/
  # install npm packages
  - pushd test/solidity
  - npm install
  - npm install -g "$TRUFFLE_VERSION"
  - npm install -g ganache-cli
  - popd
  
before_script:
  - go build -ldflags "$LDFLAG" -o protoc-gen-sol
  - pushd test
  - bash generate_sol_pb.sh
  - popd
  
script:
  - ganache-cli 2> /dev/null 1> /dev/null &
  - pushd test/solidity
  - truffle test
  - kill -9 $(lsof -t -i:8545)
  - popd
